name: mehlj-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: mehlj-lab-runners
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t docker.io/mehlj/mehlj-pipeline:latest .

  test:
    runs-on: mehlj-lab-runners
    needs: build
    steps:
    - name: Grab go dependencies
      run: go get -u github.com/gorilla/mux
    
    - name: Run unit tests
      run: go test -v api/main_test.go api/main.go
    
    - name: Lint Dockerfile
      run: hadolint Dockerfile
      
  deploy:
    runs-on: mehlj-lab-runners
    needs: [build, test]
    steps:
    - name: Push Docker image
      run: docker image push docker.io/mehlj/mehlj-pipeline:latest
      
    - name: Deploy to kubernetes
      run: ssh -o StrictHostKeyChecking=no root@k8snode0 kubectl rollout restart deployment mehlj-pipeline-deploy
